### ISSUE TITLE
`no-lib-imports` should support `io-ts`

### ISSUE THREAD

**Issue by Gurimarukin** [buildo/eslint-plugin-fp-ts#28]
I've started using your plugin and I think it's awesome!

---

Might I suggest that the `no-lib-imports` rule should also support `io-ts` and maybe other `fp-ts`-ecosystem libraries?

For example:

```ts
import * as D from 'io-ts/lib/Decoder`
```
should be **incorrect**.

But
```ts
import * as D from 'io-ts/Decoder`
```
should be **correct**.

**Comment by gabro** [comment]
Hi @Gurimarukin, thanks for the suggestion.

They idea of single plugin to rule them all (`eslint-plugin-gcanti` 😅) may be interesting but I'm currently leaning towards keeping this one focused.

I realize it may feel like unnecessary duplication, but I think a separate plugin may be more appropriate, since there may be other io-ts specific rules one may want to enforce and it would be easier to evolve plugins for different libraries at their own pace.

**Comment by Gurimarukin** [comment]
Ok, I understand  🙂
